<?php 
$this->layout('admin::layout', ['title' => 'Home']) ?>

<?php $this->push('stylesheets'); ?>
	<link rel="stylesheet" type="text/css" href="/assets/stylesheets/admin.css" />
<?php $this->end(); ?>


<section id="roles-list">
	<h1>Channels List</h1>
		<?php array_walk($channels->getIterator(), function($channel) {
		    $this->insert('partials::channels/item', ['channel' => $channel]);
		}) ?>
</section>


<?php if ($selectedChannel): ?>
    <section class="discord-channel">
        <?php array_walk($selectedChannelMessages->getIterator(), function($message) use ($members) {
            $this->insert('partials::messages/item', ['message' => $message, 'members' => $members]);
        }); ?>
    </section>
<?php endif; ?>