<div>
    <h1>
    	<?= $routeName ?>
   	</h1>
   	<div>
       	<?php  array_walk($permissions, function($permission) use ($roles, $routeName) {
       	    $this->insert('partials::roles/removable-tag', [
       	        'role' => $roles->getById($permission->getRoleId()),
       	        'url' => $this->url('admin.rbac.remove', ['routeName' => $routeName, 'roleId' => (string) $permission->getRoleId()]),
       	    ]);

       	}); ?>
   		<select onchange="location = this.value;">
   			<option value="" selected>Select a role to add</option>
   			<?php
       			$ids = array_map(function($permission) { return (string) $permission->getRoleId(); }, $permissions);
       			array_walk($roles->excludeByIds($ids)->getIterator(), function($role) use ($routeName) { ?>
       			    <option value="<?= $this->url('admin.rbac.add', ['routeName' => $routeName, 'roleId' => (string) $role->getId()]) ?>">
       			    	<?= $role->getName() ?>
       			    </option>
   			<?php }) ?>
   		</select>
   	</div>
</div>
