<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title><?=$this->e($title)?> - zend-expressive</title>
    <link rel="shortcut icon" href="assets/ico/favicon.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
    <?=$this->section('stylesheets')?>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="/">
                        <img src="/assets/images/logos/ftc-mark.png" alt="Fear the Coconut" height="48" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="https://wiki.fearthecoconut.ovh/" target="_blank" class="nav-link">
                                Le Wiki
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?= $this->url('commu') ?>" class="nav-link">
                                La Commu
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?= $this->url('admin.home') ?>" class="nav-link">
                                Administration
                            </a>
                        </li>
                    </ul>
                </div>
                <?= $nickname ?>
                <?= $this->insert('app::user-menu')?>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->section('content')?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <?php if ($this->section('footer')): ?>
                <?=$this->section('footer')?>
            <?php else: ?>
                <p>
                    &copy; 2017 - <?=date('Y')?> by Fear The Coconut. All rights reserved.
                </p>
            <?php endif ?>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <?=$this->section('javascript')?>
</body>
</html>
