<div >
    <ul class="navbar-nav mr-auto">
    	<?php if ($this->e($nickname)): ?>
    		<li class="nav-item">
    			<a href="<?= $this->url('my-profile') ?>" class="nav-link">Mon Profil</a>
    		</li>
    		<li class="nav-item">
    			<a href="<?= $this->url('logout') ?>" class="nav-link">Logout</a>
    		</li>
        <?php else: ?>
    		<li class="nav-item">
    			<a href="<?= $this->url('login') ?>" class="nav-link">Login</a>
    		</li>
    	<?php endif; ?>
	</ul>
</div>