<section class="members-list-item">
	<h1>
		<a href="<?= $this->url('admin.members', ['memberId' => (string) $member->getId()]) ?>">
			<?= $member->getNickname() ?>
		</a>
	</h1>
	<div class="member-roles">
		<?php array_walk($member->getRolesIds()->getIterator(), function ($roleId) use ($roles) {
		    $this->insert('partials::roles/tag', ['role' => $roles->getById($roleId)]);
        }); ?>
	</div>
</section>